In [3]:
import numpy as np
crops = np.array(['corn', 'wheat', 'soy', 'barley', 'oats'])
# Access single element (zero-indexed)
print(crops[0])
print(crops[-1])
# Access multiple elements
print(crops[1:4])
print(crops[::2])

corn
oats
['wheat' 'soy' 'barley']
['corn' 'soy' 'oats']


In [5]:
# Soil pH readings (3 fields × 4 samples)
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
# Single element: row 1, column 2
print(ph_levels[1, 2])
# Entire row 0
print(ph_levels[0, :])
# Entire column 3
print(ph_levels[:, 3])

6.9
[6.5 6.8 6.3 6.7]
[6.7 7.2 6.3]


In [6]:
# First 2 rows, first 3 columns
sub_array = ph_levels[0:2, 0:3]
print(sub_array)
# Every other row, all columns
print(ph_levels[::2, :])

[[6.5 6.8 6.3]
 [7.1 7.  6.9]]
[[6.5 6.8 6.3 6.7]
 [6.2 6.4 6.1 6.3]]


In [8]:
temperatures = np.array([72, 85, 91, 68, 95, 70, 88])
# Create a boolean array (mask)
hot_days = temperatures > 85
print(hot_days)
# Use mask to filter original array
print(temperatures[hot_days])
# Can do it in one line
print(temperatures[temperatures > 85])

[False False  True False  True False  True]
[91 95 88]
[91 95 88]


In [9]:
# Combine conditions with & (and), | (or)
moderate = temperatures[(temperatures >= 70) &
(temperatures <= 85)]
print(moderate)
# Find extreme values (very hot OR very cold)
extreme = temperatures[(temperatures > 90) |
(temperatures < 70)]
print(extreme)

[72 85 70]
[91 68 95]


In [10]:
# Crop yields in tons
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
# Add arrays
total_yield = field_a + field_b
print(total_yield)
# Subtract to find difference
difference = field_a - field_b
print(difference)
# Multiply each by a constant
doubled = field_a * 2
print(doubled)

[238 275 280 260]
[ 2 -5  4 -4]
[240 270 284 256]


In [11]:
# Python list approach (slow!)
result = []
for i in range(len(field_a)):
 result.append(field_a[i] + field_b[i])

In [12]:
# Square roots
areas = np.array([100, 144, 225, 169])
sides = np.sqrt(areas)
# [10. 12. 15. 13.]
# Exponentiation
growth = np.exp([0, 1, 2])
# [1. 2.718 7.389]
# Logarithms
np.log10([10, 100, 1000])
# [1. 2. 3.]

array([1., 2., 3.])

In [14]:
# Work with radians
angles = np.array([0, np.pi/2, np.pi])
sines = np.sin(angles)
# [0. 1. 0.]
cosines = np.cos(angles)
# [1. 0. -1.]
tangents = np.tan(angles)
# [0. inf 0.]

In [15]:
prices = np.array([19.99, 24.51, 30.25])
# Round to nearest integer
np.round(prices)
# [20. 25. 30.]
# Floor (round down)
np.floor(prices)
# [19. 24. 30.]
# Ceiling (round up)
np.ceil(prices)
# [20. 25. 31.]

array([20., 25., 31.])

In [18]:
daily_rainfall = np.array([0.2, 0.0, 0.5, 1.2, 0.3, 0.1, 0.0])
# Sum
total = np.sum(daily_rainfall)
# Mean (average)
average = np.mean(daily_rainfall)
# Standard deviation
variability = np.std(daily_rainfall)
# Min and Max
driest = np.min(daily_rainfall) # 0.0
wettest = np.max(daily_rainfall) # 1.2

In [21]:
# Crop yields: 3 fields × 4 years
yields = np.array([
 [120, 125, 130, 135],
 [115, 120, 122, 128],
 [130, 135, 140, 142]
])
# Average across all data
overall_avg = np.mean(yields)
# Average per field (across years)
field_avgs = np.mean(yields, axis=1)
# Average per year (across fields)
year_avgs = np.mean(yields, axis=0)

In [22]:
# Add scalar to array
temps = np.array([70, 72, 68])
adjusted = temps + 5
# The scalar 5 is broadcast to [5, 5, 5]

In [23]:
# Base prices for 3 products
base_prices = np.array([[10], [20], [30]]) # 3×1
# Discounts for 4 stores
discounts = np.array([0.9, 0.85, 0.95, 0.88]) # 1×4
# Broadcast multiplication
final_prices = base_prices * discounts
print(final_prices)

[[ 9.   8.5  9.5  8.8]
 [18.  17.  19.  17.6]
 [27.  25.5 28.5 26.4]]


In [25]:
# Simulated hourly temperature data (4 sensors × 24 hours)
np.random.seed(42) # For reproducibility
sensors = np.random.normal(loc=75, scale=5, size=(4, 24))
# Round to 1 decimal place
sensors = np.round(sensors, 1)
# Problem 1: Find all readings above 82°F (danger threshold)
overheating = sensors > 82
critical_temps = sensors[overheating]
print(f"Critical readings: {len(critical_temps)} occurrences")
print(f"Hottest reading: {np.max(sensors):.1f}°F")
# Problem 2: Calculate statistics per sensor
for i in range(4):
    sensor_data = sensors[i, :]
    print(f"Sensor {i+1}:")
    print(f" Average: {np.mean(sensor_data):.1f}°F")
    print(f" Range: {np.min(sensor_data):.1f}°F to {np.max(sensor_data):.1f}°F")
    print(f" Std Dev: {np.std(sensor_data):.1f}°F")
# Problem 3: Calculate hourly averages (across all sensors)
hourly_avg = np.mean(sensors, axis=0)
hottest_hour = np.argmax(hourly_avg)
print(f"Hottest hour: Hour {hottest_hour} ({hourly_avg[hottest_hour]:.1f}°F)")

Critical readings: 7 occurrences
Hottest reading: 84.3°F
Sensor 1:
 Average: 74.3°F
 Range: 65.4°F to 82.9°F
 Std Dev: 4.8°F
Sensor 2:
 Average: 73.7°F
 Range: 65.2°F to 84.3°F
 Std Dev: 4.3°F
Sensor 3:
 Average: 75.5°F
 Range: 66.2°F to 82.7°F
 Std Dev: 4.3°F
Sensor 4:
 Average: 74.3°F
 Range: 61.9°F to 82.8°F
 Std Dev: 4.8°F
Hottest hour: Hour 17 (78.0°F)


In [26]:
arr = np.array([1, 2, 3, 4, 5])
slice_view = arr[1:4]
slice_view[0] = 999
print(arr) # [1, 999, 3, 4, 5] - original changed!

[  1 999   3   4   5]


In [27]:
a = np.array([1, 2, 3])
result = a / 2 # [0.5, 1.0, 1.5] ✓
result = a // 2 # [0, 1, 1] - floor division

In [28]:
# Float32 uses half the memory of float64
large_array = np.zeros((1000, 1000), dtype=np.float32)

In [29]:
# Bad (slow)
for i in range(len(arr)):
 arr[i] = arr[i] ** 2
# Good (fast)
arr = arr ** 2