In [1]:
# Traditional python list
temps_list=[72,75,68,71,74,69,73]

In [2]:
# Convert to numpy array
import numpy as np
temps_array=np.array([72,75,68,71,74,69,73])

In [3]:
print(temps_list)
print(type(temps_array))

[72, 75, 68, 71, 74, 69, 73]
<class 'numpy.ndarray'>


In [8]:
# Temperature from 3 sensors over 5 days
season_temps=np.array([
    [72,70,71],
    [75,73,74],
    [68,67,69],
    [71,70,72],
    [74,73,72]
])
print(season_temps)
print(f"shape:{season_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 73 72]]
shape:(5, 3)


In [13]:
sequence=np.arange(0,9,5)
print(sequence)

[0 5]


In [15]:
arr=np.array([[1,2,3], [4,5,6]])
print(arr.ndim)

2


In [16]:
arr=np.array([[1,2,3], [4,5,6]])
print(arr.shape)

(2, 3)


In [17]:
arr=np.array([[1,2,3], [4,5,6]])
print(arr.size)

6


In [18]:
arr=np.array([1,4,5,7,4,2,3])
print(arr.dtype)

int64


In [19]:
arr=np.array([1,2,3])
print(arr.itemsize)


8
